#!/bin/bash

CONFIG="$HOME/.config/hypr/waybar/catppuccin/config"
STYLE="$HOME/.config/hypr/waybar/catppuccin/style.css"

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
